/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class my_native_TestNative */

#ifndef _Included_my_native_TestNative
#define _Included_my_native_TestNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     my_native_TestNative
 * Method:    helloNative1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_my_1native_TestNative_helloNative1
  (JNIEnv *, jobject);

/*
 * Class:     my_native_TestNative
 * Method:    helloNative2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_my_1native_TestNative_helloNative2
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
